name: todo_list_flutter
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  grouped_list: ^5.1.2
  json_annotation: ^4.8.1
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.0
  nanoid: ^1.0.0
  drift: ^2.16.0
  dynamic_color: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.16.0
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
